# این فایل تنظیمات عمومی Gradle پروژه را نگهداری می‌کند.
# حداکثر حافظه JVM برای Buildهای Compose روی 3 گیگابایت تنظیم می‌شود.
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8

# پروژه کاملاً بر پایه AndroidX است.
android.useAndroidX=true

# سبک استاندارد رسمی Kotlin برای فرمت کد استفاده می‌شود.
kotlin.code.style=official

# R Class غیرترانزیتی باعث کاهش وابستگی غیرضروری بین Resourceها می‌شود.
android.nonTransitiveRClass=true
